In [1]:
import os
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
this_dir = os.getcwd()
datadir = this_dir.split('notebooks')[0] + 'data/'
data_in = pd.read_csv(datadir + 'raw/train.csv', keep_default_na=False, na_values=['_'])
data_test = pd.read_csv(datadir + 'raw/test.csv', keep_default_na=False, na_values=['_'])

In [5]:
print(np.where(data_test['Utilities']=='NA'))
print(np.where(data_test['MSZoning']=='NA'))
print(np.where(data_test['Exterior1st']=='NA'))
print(np.where(data_test['Exterior2nd']=='NA'))
print(np.where(data_test['KitchenQual']=='NA'))
print(np.where(data_test['Functional']=='NA'))
print(np.where(data_test['SaleType']=='NA'))

(array([455, 485]),)
(array([ 455,  756,  790, 1444]),)
(array([691]),)
(array([691]),)
(array([95]),)
(array([ 756, 1013]),)
(array([1029]),)


In [8]:
for col in data_test.columns:
    print(col, ': ', data_test[col].loc[455])

Id :  1916
MSSubClass :  30
MSZoning :  NA
LotFrontage :  109
LotArea :  21780
Street :  Grvl
Alley :  NA
LotShape :  Reg
LandContour :  Lvl
Utilities :  NA
LotConfig :  Inside
LandSlope :  Gtl
Neighborhood :  IDOTRR
Condition1 :  Norm
Condition2 :  Norm
BldgType :  1Fam
HouseStyle :  1Story
OverallQual :  2
OverallCond :  4
YearBuilt :  1910
YearRemodAdd :  1950
RoofStyle :  Gable
RoofMatl :  CompShg
Exterior1st :  Wd Sdng
Exterior2nd :  Wd Sdng
MasVnrType :  None
MasVnrArea :  0
ExterQual :  Fa
ExterCond :  Fa
Foundation :  CBlock
BsmtQual :  NA
BsmtCond :  NA
BsmtExposure :  NA
BsmtFinType1 :  NA
BsmtFinSF1 :  0
BsmtFinType2 :  NA
BsmtFinSF2 :  0
BsmtUnfSF :  0
TotalBsmtSF :  0
Heating :  GasA
HeatingQC :  TA
CentralAir :  N
Electrical :  FuseA
1stFlrSF :  810
2ndFlrSF :  0
LowQualFinSF :  0
GrLivArea :  810
BsmtFullBath :  0
BsmtHalfBath :  0
FullBath :  1
HalfBath :  0
BedroomAbvGr :  1
KitchenAbvGr :  1
KitchenQual :  TA
TotRmsAbvGrd :  4
Functional :  Min1
Fireplaces :  0
Firepl

In [6]:
type(data_in['OverallCond'].iloc[0])

numpy.int64

In [7]:
num_data = len(data_in)
num_val = int(np.round(num_data/4))
p = np.random.permutation(num_data)
data_shuff = data_in.sample(frac=1)
data_val = data_shuff.iloc[0:num_val]
data_train = data_shuff.iloc[num_val+1:]
data_train.to_csv(datadir + 'tvt/train.csv', index=False)
data_val.to_csv(datadir + 'tvt/val.csv', index=False)
data_test.to_csv(datadir + 'tvt/test.csv', index=False)
